name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Создание .env файла
        run: |
          touch .env
          echo login=${{ secrets.LOGIN }} >> .env
          echo password=${{ secrets.PASSWORD }} >> .env
          cat .env    
      - name: Запуск ui тестов через docker
        run: sh start.sh
