name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка git
        uses: actions/checkout@v3 
      - name: Создание .env файла
        run: |
          touch .env
          echo login=${{ secrets.LOGIN }} >> .env
          echo password=${{ secrets.PASSWORD }} >> .env
          cat .env    
      - name: Запуск ui тестов через docker
        run: sh start.sh
      - name: Получение историй allure-results
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Получение отчета allure
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history/allure-history
          keep_reports: 5
