name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка git через модуль checkout
        uses: actions/checkout@v4.1.7
      - name: Запуск ui тестов через docker
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: sh start.sh
